apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emme-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: api.emme.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emme-platform
                port:
                  number: 80
  tls:
    - hosts:
        - api.emme.app
      secretName: emme-platform-tls
