style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '0'
      - '1'
      - '2'
      - '12'
      - '25'
      - '8081'
  WildcardImport:
    active: false

naming:
  PackageNaming:
    active: true

complexity:
  LongParameterList:
    active: true
    allowedFunctionParameters: 6
    allowedConstructorParameters: 7
