replicaCount: 2

image:
  repository: ghcr.io/migangdelzar/emme-service-studio-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

livenessProbe:
  path: /actuator/health/liveness
readinessProbe:
  path: /actuator/health/readiness
startupProbe:
  path: /actuator/health

postgresql:
  enabled: true
  auth:
    database: emme
    username: emme

redis:
  enabled: true
