apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emme.fullname" . }}
  labels: {{- include "emme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "emme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "emme.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8081
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8081
          resources: {{- toYaml .Values.resources | nindent 12 }}
