apiVersion: v1
kind: Service
metadata:
  name: {{ include "emme.fullname" . }}
  labels: {{- include "emme.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
  selector: {{- include "emme.selectorLabels" . | nindent 4 }}
