apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: emme-local

images:
  - name: ghcr.io/emme/studio-api
    newTag: dev

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: studio-api
      spec:
        replicas: 1
