spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emme
    username: emme
    password: emme
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    com.emme: DEBUG
    org.springframework.modulith: DEBUG
