spring:
  application:
    name: emme-platform
  modulith:
    events:
      externalization:
        enabled: ${EMME_KAFKA_EVENTS_ENABLED:true}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    com.emme: INFO
    org.springframework: WARN
