spring:
  application:
    name: emme-platform
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    com.emme: INFO
    org.springframework: WARN
