apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../components/network-policies

namespace: emme-prod

images:
  - name: ghcr.io/migangdelzar/emme-service-studio-api
    newTag: latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: studio-api
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: studio-api
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "1000m"
                  limits:
                    memory: "1Gi"
                    cpu: "2000m"
